### ISSUE TITLE
potential user .. gets an error 404

### ISSUE THREAD

**Issue by aroundmyroom** [Libresonic/libresonic#189]
debian,
tomcat is being installed properly , I get a 'it works'

When downloaded latest release and put it in
/var/lib/tomcat8/webapps/ and restart tomcat8 I see following:

Dec 24, 2016 5:06:02 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat8/webapps/libresonic-v6.1.war has finished in 55,424 ms
Dec 24, 2016 5:06:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat8/webapps/ROOT
Dec 24, 2016 5:06:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat8/webapps/ROOT has finished in 832 ms
Dec 24, 2016 5:06:02 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Dec 24, 2016 5:06:02 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 56725 ms

but than I get
HTTP Status 404 - /libresonic/index.view

mmmm .. what did I miss in the read.me? 

thanks ..

**Comment by muff1nman** [comment]
Is there anything in the libresonic.log file? The output provided is Catalina.out I assume?

**Comment by aroundmyroom** [comment]
no output in the /var/libresonic logfile, output is indeed Catalina.out

**Comment by muff1nman** [comment]
Try renaming the war to just libresonic.war and redeploy.

**Comment by aroundmyroom** [comment]
nope.. that would be the most easiest way to resolve it ..

**Comment by aroundmyroom** [comment]
libresonic does not want to start

`[2016-12-24 18:31:18,461] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.libresonic.player.dao.PlayerDao] for                                           bean with name 'playerDao' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: problem with class fi                                          le or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsup                                          ported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1144)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapabl                                          eBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:758)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFa                                          ctory.java:422)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationC                                          ontext.java:728)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:255)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:199)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:45)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4832)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:461)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1495)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1432)
        at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:289)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:618)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0                                           (unable to load class org.libresonic.player.dao.PlayerDao)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2476)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:853)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1263)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1146)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:211)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:385)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1138)
        ... 58 more
Dec 24, 2016 6:31:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Dec 24, 2016 6:31:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/libresonic] startup failed due to previous errors
Dec 24, 2016 6:31:18 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat8/webapps/libresonic.war has finished in 24,266 ms
`

**Comment by muff1nman** [comment]
Looks like it's complaining about missing Java 8. What's the output of `java -version`

**Comment by aroundmyroom** [comment]
uhm
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

**Comment by muff1nman** [comment]
Bingo. You'll need to install Java 8 and then use Debian's update-alternatives or equivalent to use it over Java 7.

**Comment by aroundmyroom** [comment]
ok .. that's indeed whats written  in the doc, but does not match the apt-get  part
nevermind .. mmm, did some updates and changes.. 

root@myhost:~# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

but still not start..

**Comment by muff1nman** [comment]
What's in your logs now?

**Comment by aroundmyroom** [comment]
same
`WARN  org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method 'shutdown' failed on bean with name 'cxf': org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.libresonic.player.dao.PlayerDao] for bean with name 'playerDao' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)
[2016-12-24 19:12:12,891] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.libresonic.player.dao.PlayerDao] for bean with name 'playerDao' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)`

**Comment by aroundmyroom** [comment]
mmm tomcat still thinks its on 1.7.0_111-b01 .. uhmmm

**Comment by muff1nman** [comment]
Do you have JAVA_HOME set? `echo $JAVA_HOME` You shouldn't need to, but I'm curious if yours is still set to java 7. 

Tomcat has its own logic for picking up the java version. To override it, you could try `export JAVA_HOME=/opt/jdk/jdk1.8.0_111` and restart tomcat, or even just adding it before the catalina.sh like `JAVA_HOME=/opt/jdk/jdk1.8.0_111 catalina.sh start`

Regardless, sounds like we might need to update the installation docs for debian.

**Comment by aroundmyroom** [comment]
solved it .. 
the solution was to modify the info for tomcat8 in:
/etc/default/tomcat8

needed to uncomment
JAVA_HOME=
and redirect it to: /opt/jdk/jdk1.8.0_111/
even if the enviroment variabele was set it found the 'older' version causing libresonic not to run
changing the JAVA_HOME gave me the correct JAVA and .. 
I have a login page now ;-)

Thanks for the help, it pointed me in the correct direction !

**Comment by muff1nman** [comment]
Oh good. I'll close this issue. Feel free to open another one if you run into something else.

**Comment by aroundmyroom** [comment]
let's see if it can index +150.000 songs ..

**Comment by muff1nman** [comment]
You might be interested in the external database support. Its not quite ready yet, but I think some folks have hit a wall with the builtin hsqldb. If you do use hsqldb, keep backups of the db directory as its been known to get corrupted.

**Comment by aroundmyroom** [comment]
Yup ..thanks I was switching back and forth between Subsonic & Madsonic, due to performance issues, in the end it was my VMWARE machine causing the issues .. 
As I do not like the madsonic license I went back to subsonic. 6.0 is working ok for me, but I want an alternative with 'active' development. if external db is ready for testing I am for sure 'in' .. 

Performance wise it needs a lot of updates like madsonic, cause the db is slow compared to the indexing of madsonic ..  +150.000 have been indexed now . (in 2 hours . .) not 100% ready yet.
