### ISSUE TITLE
Changing default media path properties break Liquidbase migrations

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#236]
When changing one of the default media path properties (e.g. `libresonic.defaultMusicFolder`), Liquidbase fails with the following error :

```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          classpath:liquibase/legacy/schema26.xml::schema26_002::muff1nman was: 7:24d1b10cd19f1e6342fe21dadca1eff1 but is now: 7:ec7b1d49e84c1baf05e30fd7dd5fc38c
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:266) ~[liquibase-core-3.5.1.jar!/:na]
        at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:935) ~[liquibase-core-3.5.1.jar!/:na]
        at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:912) ~[liquibase-core-3.5.1.jar!/:na]
        at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:891) ~[liquibase-core-3.5.1.jar!/:na]
        at liquibase.integration.spring.SpringLiquibase.generateRollbackFile(SpringLiquibase.java:414) ~[liquibase-core-3.5.1.jar!/:na]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:390) ~[liquibase-core-3.5.1.jar!/:na]
        at org.libresonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:24) ~[classes!/:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        ... 23 common frames omitted
```

**Comment by muff1nman** [comment]
Good catch. How did you run into this? I'm wondering, is there a valid use case for changing the default media folder after the first startup? The one use I see for even changing it at all is for package maintainers but in that case the value wouldn't change after the first startup.

**Comment by fxthomas** [comment]
I was actually trying out some configuration changes, and this happened. It got me surprised for a while. Should these parameters actually exist since they are not used after the initial setup? We can always configure them in the admin interface!

**Comment by muff1nman** [comment]
The default media path is inserted into the database on first run, so it's not possible to change it via the admin interface.

**Comment by muff1nman** [comment]
I still don't think there is a valid use case for changing that parameter after first startup. Let me know if you think otherwise.
