### ISSUE TITLE
6.2-beta1 wont startup

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#274]
Investigating:

```
05-Mar-2017 18:41:57.589 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/libresonic]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@35c8b09b]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4831)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4963)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
        ... 10 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@18de1c03]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:111)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:141)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:692)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: error in opening zip file
        at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:139)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        ... 16 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:136)
        ... 17 more


```

**Comment by muff1nman** [comment]
This was just an error on my part.

**Comment by jonesints** [comment]
Can you tell me what the "error" was on your part? I'm having the same issue, my log shows something similar:


`cat /var/log/tomcat8/catalina.out
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:52 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version: Apache Tomcat/8.0.14 (Debian)
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:   Feb 18 2017 05:56:46
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:  8.0.14.0
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:        Linux
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:     4.4.50-v7+
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:   arm
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:    1.7.0_121-b00
May 01, 2017 10:06:53 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:     Oracle Corporation
May 01, 2017 10:06:58 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
May 01, 2017 10:06:58 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
May 01, 2017 10:06:59 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 6347 ms
May 01, 2017 10:06:59 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
May 01, 2017 10:06:59 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.14 (Debian)
May 01, 2017 10:06:59 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat8/webapps/ROOT
May 01, 2017 10:07:18 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
May 01, 2017 10:07:19 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat8/webapps/ROOT has finished in 19,737 ms
May 01, 2017 10:07:19 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
May 01, 2017 10:07:19 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 20225 ms
May 01, 2017 10:09:09 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat8/webapps/libresonic.war
May 01, 2017 10:09:09 AM org.apache.catalina.startup.ContextConfig beforeStart
SEVERE: Exception fixing docBase for context [/libresonic]
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:91)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:94)
	at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:618)
	at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:744)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1703)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

May 01, 2017 10:09:09 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/libresonic]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
`

I'm running Tomcat8 with oracle 1.8 on a raspberry pi:

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

echo $JAVA_HOME returns /usr/bin/java

**Comment by muff1nman** [comment]
Please add formatting when pasting logs

**Comment by jonesints** [comment]
Apologies, still new to gh. Any clue as to what could be the issue? The first error that seems to show up on the log is: 

> SEVERE: Exception fixing docBase for context [/libresonic]

**Comment by muff1nman** [comment]
In my case and probably yours too was that the war file was invalid. Verify the file you downloaded.

**Comment by jonesints** [comment]
Seems it wasn't a corrupt war file but a tomcat8 issue. Reinstalled and working.
