### ISSUE TITLE
Cannot start DLNA server - URI is not hierarchical when using Standalone(Spring Boot) packaging

### ISSUE THREAD

**Issue by izderadicka** [Libresonic/libresonic#320]
When UPnP/DLNA server is enabled it fails to start with error below  -   tried to enter different URLs or leave field empty in settings (not sure should be there as this setting was not available in Subsonic,  is DLNA server supposed to run on different port then libresonic?).

I'm running libresonic 6.2-beta2 on linux (ubuntu 64 bit) with oracle java 1.8.

```
2017-03-27 10:57:38.893 ERROR --- o.l.player.service.UPnPService           : Failed to start UPnP/DLNA media server: java.lang.IllegalArgumentException: URI is not hierarchical

java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418) ~[na:1.8.0_121]
	at org.fourthline.cling.model.meta.Icon.<init>(Icon.java:76) ~[cling-core-2.0.1.jar!/:na]
	at org.libresonic.player.service.UPnPService.createMediaServerDevice(UPnPService.java:120) ~[classes!/:6.2.beta2]
	at org.libresonic.player.service.UPnPService.setMediaServerEnabled(UPnPService.java:97) ~[classes!/:6.2.beta2]
	at org.libresonic.player.controller.DLNASettingsController.handleParameters(DLNASettingsController.java:85) [classes!/:6.2.beta2]
	at org.libresonic.player.controller.DLNASettingsController.handlePost(DLNASettingsController.java:67) [classes!/:6.2.beta2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
```

**Comment by muff1nman** [comment]
Reproduced. It actually has nothing to do with the URL you are inputting, but rather how we are fetching the Icon from the classpath when it is within the zipped war. A work around is to deploy the app on tomcat.

**Comment by muff1nman** [comment]
Resolved on develop branch.
