### ISSUE TITLE
6.2B2 "confused" music playback

### ISSUE THREAD

**Issue by texneus** [Libresonic/libresonic#321]
I had a very strange thing happen to me this morning.  This may have been a complete fluke (still researching) but this seemed significant enough to at warrant a heads up.

Basically what happened is, when using random play on Dsub, only the first track played correctly.  From memory (so the details may not be exact),  the second track played the indicated song, but displayed cover art from a different artist.  The third song was the right cover art, but was playing a track from a different artist.  The fourth track was the right cover art (I think) and artist, but not the indicated song.   On and on where nothing matched up 100%.  I eventually stopped playback, deleted my cache, and upon restart it seemed to be OK.

Install details:
- Installed 6.2 beta 2 last night
- Clean install of Beta 2 into a new, clean jail
- Used Springboot feature (no Tomcat)
- 6.2 beta 1 was working correctly under Tomcat8 previously
- Proxied via Nginx over HTTPS
- NAS4Free 11.0.0.4 (FreeBSD 11.0-P7) OS

Other potential factors:
- Even though flushing cache seemed to resolve it, none of the songs affected were already cached.
- DSUB client on mobile network
- DSUB set to random play
- Large music library (~20,000 titles).
- Streaming is set to convert all audio to .ogg w/ffmpeg
- Testing at home (on local and mobile network) immediately after install did not show any problem
- The fifth or so track wouldn't download at all but skipping past it was no problem (need to follow-up and see if there is a corrupt file).  However tracks both before and after we're impacted.
- Verified my wife was not playing audio at the same time...so no chance of "crossed streams".

I owe:
Longer playtime...is this repeatable?
Log files from this morning
Troubleshoot non-playing track

**Comment by muff1nman** [comment]
Let us know if you can reproduce with steps, logs, etc.

**Comment by texneus** [comment]
More info as I see several exceptions being thrown in the logs.  Some captures from my phone to better illustrate what I was seeing and a reconstruction of tracks played:

Que     Artist  | Album | Track  --> What actually played
1. Sade | Soldier of Love | 01 The Moon and the Sky.mp3  --> (same)
   Note:  Log shows 2 exceptions starting at timestamp 2017-03-28 08:14:58.831 before file was transcoded.

2.  Bread | The Best of Bread | 05 It Don't Matter to Me.mp3  --> Same, except cover art displayed was from Pet Shop Boys | Please.
  Log shows no errors.
![screenshot_2017-03-28-08-20-58](https://cloud.githubusercontent.com/assets/23441049/24433828/ffac21ae-13f0-11e7-90c9-f792c147b758.jpg)

3. Steve Winwood | 20th Century Masters- The Millennium Collection- The Best of Steve Winwood | 1-09 John Barleycorn.mp3 --> (same)
   Note:  Log shows no errors.

4. Tony Bennett | Playin' With My Friends- Bennett Sings the Blues | 12 Undecided Blues.mp3   --> Same, except DSub claimed it was playing track 11 (New York State of Mind) from same album.
  Note:  Following transcoding Libresonic threw many exceptions starting at 2017-03-28 08:20:32.451

5. Blues Traveler | Four | 02 Stand.mp3 --> Same, except claimed to be playing Crowded House | Time on Earth | A Sigh.
![screenshot_2017-03-28-08-34-43](https://cloud.githubusercontent.com/assets/23441049/24434136/41cbb822-13f3-11e7-83c3-d4d82229bea4.jpg)
Note:  Following transcoding, the log again throws many exceptions starting at 2017-03-28 08:21:06.939

At this point the track that would not down load came up and did nothing.  There are no log entries associated with this file at all.  I was going to clear the playlist and start over in Dsub but since the cache was also "spoiled", that is why I cleared it at this point.  Following this action, there were no further issues observed in Dsub and I played and tried various things for 4 hours or so.  This included playing (or rather downloading) the entire album of the "bum" track that didn't play earlier.  No problems!  I still see a lot of exceptions in the log though...

I will upload the full log shortly...

**Comment by texneus** [comment]
Log attached.  This is everything from first run late last night until about 8:20pm this evening.  If you need help with anything please let me know.  If I can get this to repeat I'll be sure to pop in again!

[libresonic.log.zip](https://github.com/Libresonic/libresonic/files/877634/libresonic.log.zip)

**Comment by muff1nman** [comment]
You have quite the variety of exceptions growing in your log file. I think it makes sense to address them one by one and see if fixing any of them addresses your issue. First one is easy: add an entry to your /etc/hosts file so that test.local resolves to 127.0.0.1. Something like this might do:

```
127.0.0.1     test.local
```

**Comment by muff1nman** [comment]
Also what database and version of that database are you using?

**Comment by muff1nman** [comment]
Next, for the lines like this:
```
Failed to list children for /mnt/Media/Music/Main/Tish Hinojosa/The Best of The Sandia- Watermelon 1991-1992/17 ??rbolito (English Version).mp3
```
See #285. Particularly, try the following, but be careful as `/etc/init/tomcat.conf`might not be the right file for your system.

> After adding:
env LC_ALL=en_US.UTF-8
to my /etc/init/tomcat.conf
the issues have disappeared.

**Comment by muff1nman** [comment]
That leaves the following exceptions. These are quite bothersome - I haven't seen these before. 
```
java.lang.NullPointerException: null
	at org.libresonic.player.controller.AvatarController.getAvatar(AvatarController.java:93) ~[classes!/:6.2.beta2]
	at org.libresonic.player.controller.AvatarController.handleRequest(AvatarController.java:64) ~[classes!/:6.2.beta2]
	at org.libresonic.player.controller.RESTController.getAvatar(RESTController.java:1966) ~[classes!/:6.2.beta2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
```

```
java.lang.NullPointerException: null
	at org.libresonic.player.controller.StreamController.getFileLength(StreamController.java:280) ~[classes!/:6.2.beta2]
	at org.libresonic.player.controller.StreamController.handleRequest(StreamController.java:156) ~[classes!/:6.2.beta2]
	at org.libresonic.player.controller.RESTController.stream(RESTController.java:1373) ~[classes!/:6.2.beta2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
```

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [insert into play_queue_file(play_queue_id, media_file_id) values (?, ?)]; Integrity constraint violation - no parent PQF_PQ_FK table: PLAY_QUEUE in statement [insert into play_queue_file(play_queue_id, media_file_id) values (?, ?)]; nested exception is java.sql.SQLException: Integrity constraint violation - no parent PQF_PQ_FK table: PLAY_QUEUE in statement [insert into play_queue_file(play_queue_id, media_file_id) values (?, ?)]
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:941) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.libresonic.player.dao.AbstractDao.update(AbstractDao.java:82) ~[classes!/:6.2.beta2]
	at org.libresonic.player.dao.PlayQueueDao.savePlayQueue(PlayQueueDao.java:61) ~[classes!/:6.2.beta2]
	at org.libresonic.player.dao.PlayQueueDao$$FastClassBySpringCGLIB$$463ea98e.invoke(<generated>) ~[classes!/:6.2.beta2]
```

The second one I'll have to look into. However, it would be interesting to see if creating a new user makes those two issues go away. Do this after fixing the other small things above.

**Comment by texneus** [comment]
1. "First one is easy: add an entry to your /etc/hosts file so that test.local resolves to 127.0.0.1"...Done!

2. "Also what database and version of that database are you using?"...Is 'Whatever Libresonic comes with' an acceptable answer?  I have not setup any extra database...

3. "Particularly, try the following, but be careful as /etc/init/tomcat.conf might not be the right file for your system."...Ah yes, meant to try that, but there does not seem to be any tomcat.conf file on my system at all.  I'm running the .WAR standalone via springboot.  There are some tomcat.123456789012345670.4040 (tomcat dot <a bunch of numbers> dot <port number>) in the tmp directory, but that is all I see for tomcat files.

Current status:  Still has not repeated despite continued exceptions in the logs.  I'm now leaning towards this being a total but temporary failure on DSub's end, but absolutely let's get the exceptions figured out.  Let me know what you need...

**Comment by texneus** [comment]
A bit of progress on part 3.  I could find absolutely nothing about locale + tomcat + FreeBSD.  Everything I do find suggests it's up to the user to define it in their login.  The problem in my case is slightly more complicated.  As I'm running Libresonic in a FreeBSD jail, nothing actually logs in to run Libresonic.  Therefore the suggested locale tweaks to the login.conf are ineffective.  What I ended up doing was creating a script to start Libresonic which also defines the necessary environment variable as follows:

```
LANG=en_US.UTF-8
sudo -u www java -Dserver.port=4040 -Dserver.address=127.0.0.1 -Dserver.contextPath=/libresonic -jar /var/libresonic/libresonic.war &
```
(Note:  The two lines starting with "sudo" is actually a single, long command

Unfortunately I never could get UTF-8 tracks to rescan in the existing database, so I reset Libresonic and loosing the old logs in the process.  Regardless, the startup process is now much cleaner as evidenced by the logs.  Also the exceptions do still exist following setup of DSub and testing a single track...New logs attached.  I will try the new user suggestion after a few days to build up new log entries...
[libresonic2.log.zip](https://github.com/Libresonic/libresonic/files/887359/libresonic2.log.zip)

**Comment by texxasrulez** [comment]
I have had similar issues when I was using subsonic. I had to go and clear data and cache through my phone app manager, re-enter server credentials and it solved my problem. It happened every time a fresh scan of DB was performed ...

**Comment by muff1nman** [comment]
Is there anything sensitive in your database, would you mind sending it to me somehow (we can coordinate over email)? Something doesn't seem right. Or, you could try running with a clean slate and see if that helps.

**Comment by texneus** [comment]
Good news:  I figured out how to make it repeat.
Bad news:  It is repeatable...

As @texxasrulez suggests it does seem to be related to changing Libresonic versions, instances, and/or databases, but it does not seem matter if you clear cache and refresh artists or not.  All that is required is to start random play...the first instance simply trips over itself.  Clear the playlist, start a new random playlist and it's fine.  Again, I'm not convinced the issue is actually Libresonic.  The smoking gun is if Libresonic could log what track/artist/artwork the client actually requested, not just what sent...is this possible?

Steps to reproduce:
Background:   I still have 6.2 beta 1 installed so I can switch very easilly between beta 1 and beta 2 on my NAS4Free server by simply shutting down one Libresonic jail and starting the other.  Both servers are configured identically, same IP, libraries, etc.  It should, at least on paper, be no different than updating from one version to another, or regressing to an old version.

In the Dsub app, clear the cache if you like (it doesn't seem to matter)

On the server, shut down one Libresonic instance and start the other.

Back to the DSub app, refresh the library by dragging down the top of the screen when you are in library view.  Now start random play (press the shuffle button in the top right).

Result:  Behavior as reported in original post -- The track actually playing does not match the displayed cover art, artist, track, or various combinations thereof.  About 1 in 10 songs just simply will not download, but you can skip to the next track no problem.

To restore normal operation:  Stop playback, remove the current playlist, and restart random play.  Repeat as often as you like...  The cache does seem to retain the erroneous information and will need to be cleared.  For example I'm browsing the library and see an Amos Lee album with a Joe Satriani cover art, a victim of the initial random play.

@muff1nman, I assume you are talking to me.  I'm more than happy to help out, let me know.  Is there a way to send PMs here on github?

**Comment by muff1nman** [comment]
Tried the reindex and start a random playlist, but seems to work fine. @texneus Send me an email to lostonamountain at gmail dot com with a download link (google drive or something). I'd like to see whats causing some of the exceptions in your log.

**Comment by muff1nman** [comment]
For the avatar npe, that should be fixed with 8505d69dd51f5114339bee20a57e29515339ad3d. However, I don't think it should be actually causing much trouble. The biggest thing that bothers me about the most recent log output you gave me is the sql exception when creating a new player. I couldn't reproduce it even when using your database :( Are you stilling getting similar exceptions in your log output? To be specific the exception I am referring to is this:
```
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into player (id, name, type, username, ip_address, auto_control_enabled, m3u_bom_enabled, last_seen, cover_art_scheme, transcode_scheme, dynamic_ip, technology, client_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Violation of unique constraint $$: duplicate value(s) for column(s) $$: PK_PLAYER in statement [insert into player (id, name, type, username, ip_address, auto_control_enabled, m3u_bom_enabled, last_seen, cover_art_scheme, transcode_scheme, dynamic_ip, technology, client_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is java.sql.SQLException: Violation of unique constraint $$: duplicate value(s) for column(s) $$: PK_PLAYER in statement [insert into player (id, name, type, username, ip_address, auto_control_enabled, m3u_bom_enabled, last_seen, cover_art_scheme, transcode_scheme, dynamic_ip, technology, client_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
```

**Comment by texneus** [comment]
Sorry for the lengthy delay, I'm trapped having to reinstall Winders for my wife so she uses my laptop while I"m working on hers :-).  I only see the one exception.  I tried to reproduce it by creating a new user, all I see is the avatar exception.  I don't see any such exception in the 6 beta 1 logs either.  I do see a lot of StreamController exceptions in contiguous blocks though, are these of any concern?  This might be related to me trying to play in the web client which outright doesn't work for me.

ex:
`org.libresonic.player.controller.StreamController.getFileLength(StreamController.java:280) ~[classes!/:6.2.beta2]`

@texxasrulez, if you're still out there, what client do you use when you see this issue?
