### ISSUE TITLE
postgresql  ERROR while scanning media folder

### ISSUE THREAD

**Issue by cascooscuro** [Libresonic/libresonic#337]
Hi,

wile scanning media folder, Libresonic throws an error and stops the scan:

[2017-04-06 12:20:12,027] INFO MediaScannerService - Scanned media library with 10750 entries.
[2017-04-06 12:20:13,776] ERROR MediaScannerService - Failed to scan media library.
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update media_file set folder=?,type=?,format=?,title=?,album=?,artist=?,album_artist=?,disc_number=?,track_number=?,year=?,genre=?,bit_rate=?,variable_bit_rate=?,duration_seconds=?,file_size=?,width=?,height=?,cover_art_path=?,parent_path=?,play_count=?,last_played=?,comment=?,changed=?,last_scanned=?,children_last_updated=?,present=?, version=? where path=?]; ERROR: invalid byte sequence for encoding "UTF8": 0x00; nested exception is org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:941)
        at org.libresonic.player.dao.AbstractDao.update(AbstractDao.java:82)
        at org.libresonic.player.dao.MediaFileDao.createOrUpdateMediaFile(MediaFileDao.java:164)
        at org.libresonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$83a0b56b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.libresonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$17d6a963.createOrUpdateMediaFile(<generated>)
        at org.libresonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:105)
        at org.libresonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:67)
        at org.libresonic.player.service.MediaFileService.findCoverArt(MediaFileService.java:607)
        at org.libresonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:521)
        at org.libresonic.player.service.MediaFileService.updateChildren(MediaFileService.java:393)
        at org.libresonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:179)
        at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:230)
        at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:234)
        at org.libresonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:172)
        at org.libresonic.player.service.MediaScannerService.access$000(MediaScannerService.java:38)
        at org.libresonic.player.service.MediaScannerService$2.run(MediaScannerService.java:142)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
        ... 26 more

I'm Using:
Version	6.2.beta1 – March 5, 2017
Server	Apache Tomcat/8.0.41, java 1.8.0_121, Linux (448.3 MB / 940.5 MB)
and postgre DB in "jndi" mode :

        driverClassName="org.postgresql.Driver"
        url="jdbc:postgresql://localhost/libresonic?stringtype=unspecified"/>

**Comment by muff1nman** [comment]
My hunch is on this is that there is some interesting data in the tags of one of your media files. I think the first thing is to identify the file, so I've added some logging that can be enabled to see which file it is (fdcb4adb3be5401349a6028aa2eb6e0746207908). You can either wait for the next release with this change, or compile the latest from the develop branch and add the following java arg to enable the logger:

```
-Dlogging.level.org.libresonic.player.dao.MediaFileDao=TRACE 
```

**Comment by muff1nman** [comment]
6.2.beta3 will have that extra logging which will save you from having to compile yourself.

**Comment by muff1nman** [comment]
We will probably need a copy of your media file in order to figure out what is going on here. The comments above will help determine which media file is causing the issue.

**Comment by gedekay** [comment]
I'm facing the same issue, have enabled the logger, and found a folder that causes the issue. Some of the files have é and ù in their titles, but I'm not convinced those are causing the issue. What's the best way to provide a copy of the files?

**Comment by muff1nman** [comment]
Can you post your stack trace just so we can verify its the same issue? We can coordinate over email on providing a copy of the files.

**Comment by cascooscuro** [comment]
Found the media file!! just sent you the file by email.

And some more information with the issue. This problem only happens when PostgreSQL is used, if I change to HSQL  the problem does not appear.

**Comment by muff1nman** [comment]
@cascooscuro. Got it reproduced with the file you sent 👍   Just need to fix it now
