### ISSUE TITLE
 started a thread named [MediaLibraryScanner] but has failed to stop it

### ISSUE THREAD

**Issue by gerroon** [Libresonic/libresonic#453]
Hi

I am not sure what the issue is because it used to be able to scan all without issues. 

I am using it on Debian 32, Tomcat8, Libresonic 6.2. 

  
WARNING: The web application [/libresonic] appears to have started a thread named [MediaLibraryScanner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.FileChannelImpl.position0(Native Method)
 sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:288)
 org.jaudiotagger.audio.mp3.MP3AudioHeader.seek(MP3AudioHeader.java:168)
 org.jaudiotagger.audio.mp3.MP3AudioHeader.<init>(MP3AudioHeader.java:137)
 org.jaudiotagger.audio.mp3.MP3File.<init>(MP3File.java:453)
 org.jaudiotagger.audio.mp3.MP3FileReader.read(MP3FileReader.java:39)
 org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:288)
 org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:151)
 org.libresonic.player.service.metadata.JaudiotaggerParser.getRawMetaData(JaudiotaggerParser.java:75)
 org.libresonic.player.service.metadata.MetaDataParser.getMetaData(MetaDataParser.java:48)
 org.libresonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:512)
 org.libresonic.player.service.MediaFileService.updateChildren(MediaFileService.java:393)
 org.libresonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:179)
 org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:232)
 org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:236)
 org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:236)
 org.libresonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:174)
 org.libresonic.player.service.MediaScannerService.access$000(MediaScannerService.java:39)
 org.libresonic.player.service.MediaScannerService$2.run(MediaScannerService.java:143)
Jun 04, 2017 10:03:37 AM org.apache.coyote.AbstractProtocol stop

**Comment by gerroon** [comment]
And some other peculiar errors when  I restart Tomcat

        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]

2017-06-04 10:11:24.919  WARN --- o.l.player.service.SearchService         : Failed to remove Lucene lock file in org.apache.lucene.store.NIOFSDirectory@/var/libresonic/lucene2/artist_id3 lockFactory=org.apache.lucene.store.NativeFSLockFac
tory@17869db

org.apache.lucene.store.LockReleaseFailedException: Cannot forcefully unlock a NativeFSLock which is held by another indexer component: /var/libresonic/lucene2/artist_id3/write.lock
        at org.apache.lucene.store.NativeFSLock.release(NativeFSLockFactory.java:278) ~[NativeFSLock.class:3.0.3 1039909 - 2010-11-28 19:08:19]
        at org.apache.lucene.index.IndexWriter.unlock(IndexWriter.java:4907) ~[IndexWriter.class:3.0.3 1039909 - 2010-11-28 19:08:19]
        at org.libresonic.player.service.SearchService.removeLocks(SearchService.java:402) [SearchService.class:na]                                                                                                                                    at org.libresonic.player.service.SearchService.<init>(SearchService.java:92) [SearchService.class:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_73]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_73]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_73]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_73]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) [BeanUtils.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) [SimpleInstantiationStrategy.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [AbstractBeanFactory$1.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [DefaultSingletonBeanRegistry.class:4.3.7.RELEASE]                                                               at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [AbstractBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [AbstractBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351) [BeanDefinitionValueResolver.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108) [BeanDefinitionValueResolver.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [AbstractAutowireCapableBeanFactory.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [AbstractBeanFactory$1.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [DefaultSingletonBeanRegistry.class:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [AbstractBeanFactory.class:4.3.7.RELEASE]

**Comment by gerroon** [comment]
WARNING: The web application [/libresonic] appears to have started a thread named [pool-4-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.io.FileOutputStream.open0(Native Method)
 java.io.FileOutputStream.open(FileOutputStream.java:270)
 java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 java.io.FileOutputStream.<init>(FileOutputStream.java:162)
 org.libresonic.player.service.PodcastService.downloadImage(PodcastService.java:359)
 org.libresonic.player.service.PodcastService.doRefreshChannel(PodcastService.java:318)
 org.libresonic.player.service.PodcastService.access$200(PodcastService.java:65)
 org.libresonic.player.service.PodcastService$4.run(PodcastService.java:283)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
Jun 04, 2017 10:23:34 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/libresonic] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal] (value [LocaleContext]) and a value of type [org.springframework.web.servlet.DispatcherServlet$1] (value [org.springframework.web.servlet.DispatcherServlet$1@ff1ec]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 04, 2017 10:23:34 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/libresonic] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal] (value [Request attributes]) and a value of type [org.springframework.web.context.request.ServletRequestAttributes] (value [org.libresonic.player.filter.ParameterDecodingFilter$DecodingServletRequestWrapper@438a4c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 04, 2017 10:23:34 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/libresonic] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@1241e33]) and a value of type [org.springframework.security.core.context.SecurityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@5fc5858: Authentication: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@5fc5858: Principal: org.springframework.security.core.userdetails.User@ea5dfb9d: Username: kursadk; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: IS_AUTHENTICATED_ANONYMOUSLY,ROLE_ADMIN,ROLE_COMMENT,ROLE_DOWNLOAD,ROLE_JUKEBOX,ROLE_PODCAST,ROLE_SETTINGS,ROLE_SHARE,ROLE_STREAM,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 192.168.2.104; SessionId: B5EB51B8BDF29DCE639E312CE76520FF; Granted Authorities: IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_COMMENT, ROLE_DOWNLOAD, ROLE_JUKEBOX, ROLE_PODCAST, ROLE_SETTINGS, ROLE_SHARE, ROLE_STREAM, ROLE_USER]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 04, 2017 10:23:34 AM org.apache.coyote.AbstractProtocol stop

**Comment by gerroon** [comment]
Is there a detailed way to get mediascanner log to see where it is getting stuck at? It is always stuck at some number and catalina output is telling me nothing about where it is at the moment.

**Comment by muff1nman** [comment]
Just formatted your logs to see whats going on. Can't really see any sort of root cause from what I can tell. Unfortunately we dont currently have a good logger in place that will log which file its scanning, but we can definitely add one to see if youre running into a bad file of a sort.

**Comment by muff1nman** [comment]
I was going to add a better logger to the stable branch, but as stable doesn't contain #310, I put the change into develop instead at 3a9e0f33af59ffff3bb7eef729984582f1b06bc7. Just be forewarned that if you try develop, you cannot go back to stable. I would suggest backing up your libresonic home directory if you do decide to try that commit out.

**Comment by gerroon** [comment]
I want to try but I need a war file. I do not know how to run from the source.

**Comment by muff1nman** [comment]
Email me (see GitHub profile) to request an unofficial war and I'll send you a download link.

**Comment by gerroon** [comment]
@muff1nman

I do not see your email in your profile. Can you just upload to somewhere so I can download it?

**Comment by muff1nman** [comment]
https://s3-us-west-2.amazonaws.com/jar.download.andrewdemaria.com/libresonic/bcd330e7/libresonic.war

**Comment by muff1nman** [comment]
Also youll need to add a java parameter to turn on the logger:
```-Dlogging.level.org.libresonic.player.service.MediaScannerService=trace```

**Comment by gerroon** [comment]
thanks I will give it a try when I have time later.
