### ISSUE TITLE
Error when sending scrobble to last fm

### ISSUE THREAD

**Issue by dorel14** [Libresonic/libresonic#483]
Hello 
I've seen this error in logs when scrobbling to last FM 
`2017-07-29 22:09:24.774 WARN --- o.l.p.s.AudioScrobblerService : Error in Last.fm registration.
--
 
java.lang.IllegalArgumentException: Illegal character in query at index 69: http://post.audioscrobbler.com/?hs=true&p=1.2.1&c=sub&v=0.1&u=djdmd14 &t=1501358964&a=550449ffbbb4062781c2c6b54a5535e5
at java.net.URI.create(URI.java:852) ~[na:1.8.0_65]
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69) ~[httpclient-4.5.2.jar:4.5.2]
at org.libresonic.player.service.AudioScrobblerService.executeGetRequest(AudioScrobblerService.java:235) ~[classes/:6.2]
at org.libresonic.player.service.AudioScrobblerService.authenticate(AudioScrobblerService.java:172) ~[classes/:6.2]
at org.libresonic.player.service.AudioScrobblerService.scrobble(AudioScrobblerService.java:132) ~[classes/:6.2]
at org.libresonic.player.service.AudioScrobblerService.access$1000(AudioScrobblerService.java:51) ~[classes/:6.2]
at org.libresonic.player.service.AudioScrobblerService$RegistrationThread.run(AudioScrobblerService.java:277) ~[classes/:6.2]
Caused by: java.net.URISyntaxException: Illegal character in query at index 69: http://post.audioscrobbler.com/?hs=true&p=1.2.1&c=sub&v=0.1&u=djdmd14 &t=1501358964&a=550449ffbbb4062781c2c6b54a5535e5
at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_65]
at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_65]
at java.net.URI$Parser.parseHierarchical(URI.java:3111) ~[na:1.8.0_65]
at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_65]
at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_65]
at java.net.URI.create(URI.java:850) ~[na:1.8.0_65]
... 6 common frames omitted

`

**Comment by tari** [comment]
It looks like there's a trailing space in your username, which is at index 69 in that URL. Is that intentional?

Looks like AudioScrobblerService.authenticate should URL encode the username when constructing that request, though.

**Comment by dorel14** [comment]
Yes , you're right , as i rewrite correctly my username it works well , perhaps i would be nice havins a control  on this and say that username is not valid.
