### ISSUE TITLE
Error while force scan library

### ISSUE THREAD

**Issue by dorel14** [Libresonic/libresonic#484]
Hello 
When i try to force scan my library , i have this error in logs 
`

2017-08-03 20:45:21.675 INFO --- o.l.p.s.MediaScannerService : Starting to scan media library.
--
2017-08-03 20:45:22.897 ERROR --- o.l.p.s.MediaScannerService : Failed to scan media library.
 
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select id, path, folder, type, format, title, album, artist, album_artist, disc_number, track_number, year, genre, bit_rate, variable_bit_rate, duration_seconds, file_size, width, height, cover_art_path, parent_path, play_count, last_played, comment, created, changed, last_scanned, children_last_updated, present, version from media_file where path=?]; SQL state [HY000]; error code [1267]; Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='; nested exception is java.sql.SQLException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.libresonic.player.dao.AbstractDao.query(AbstractDao.java:101) ~[classes/:6.2]
at org.libresonic.player.dao.AbstractDao.queryOne(AbstractDao.java:177) ~[classes/:6.2]
at org.libresonic.player.dao.MediaFileDao.getMediaFile(MediaFileDao.java:67) ~[classes/:6.2]
at org.libresonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$83a0b56b.invoke(<generated>) ~[classes/:6.2]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.libresonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$8a1d187b.getMediaFile(<generated>) ~[classes/:6.2]
at org.libresonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:452) ~[classes/:6.2]
at org.libresonic.player.service.MediaFileService.updateChildren(MediaFileService.java:393) ~[classes/:6.2]
at org.libresonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:179) ~[classes/:6.2]
at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:232) [classes/:6.2]
at org.libresonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:174) [classes/:6.2]
at org.libresonic.player.service.MediaScannerService.access$000(MediaScannerService.java:39) [classes/:6.2]
at org.libresonic.player.service.MediaScannerService$2.run(MediaScannerService.java:143) [classes/:6.2]
Caused by: java.sql.SQLException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.41.jar:5.1.41]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.5.15]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.5.15]
at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
... 18 common frames omitted

`

**Comment by muff1nman** [comment]
```
Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='; nested exception is java.sql.SQLException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
```

Did you manually set the collations on your tables?

**Comment by dorel14** [comment]
Hi, 
No i migrate from mysql to mariadb and also update my raspbian to stretch

**Comment by muff1nman** [comment]
I would take a look at your table collations and normaize them all to utf8

**Comment by dorel14** [comment]
I rolled back to hsql db thanx to a backup i have made befor migrating to mysql and know it's OK .
